repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev:  "22.6.0"
    hooks:
    -   id: black
-  repo: local
   hooks:
   -   id: custom_script
       name: custom_script
       entry: python pre_commit_script.py
       language: system
       always_run: true
       pass_filenames: false
